(function () {
  'use strict';
  var R = window.PackPopRules, canvas = document.getElementById('game'), ctx = canvas.getContext('2d');
  var title = document.getElementById('title'), resultPanel = document.getElementById('result'), pausePanel = document.getElementById('pause-panel'), draftPanel = document.getElementById('draft'), machineHud = document.getElementById('machine-hud'), topbar = document.getElementById('topbar');
  var live = document.getElementById('live'), LOGICAL_W = 960, LOGICAL_H = 540, seed = 73421, portrait = false;
  var state = R.newRun(seed), lot = null, consumed = new Set(), destroyed = consumed, packed = consumed, aim = {x:4,y:3}, pointerDown = false, spaceHolding = false, pendingRelease = false, collectedStep = 0;
  function freshFx(){return{clock:0,phaseMs:0,tallyMs:0,hits:[],particles:[],shake:0,stamp:'',stampUntil:0,collect:null}}
  var fx = freshFx();
  var last=performance.now(), muted=false, audio=null, reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;

  function announce(s){live.textContent='';setTimeout(function(){live.textContent=s;},20)}
  function resize(){var r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);portrait=r.height>r.width;LOGICAL_W=portrait?540:960;LOGICAL_H=portrait?960:540;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(canvas.width/LOGICAL_W,0,0,canvas.height/LOGICAL_H,0,0)}
  new ResizeObserver(resize).observe(canvas); resize();
  function rnd(n){var x=Math.sin((n+seed)*12.9898)*43758.5453;return x-Math.floor(x)}
  function runCode(n){return (n>>>0).toString(36).toUpperCase().padStart(7,'0')}
  function freshSeed(){return ((Date.now()^Math.floor(performance.now()*1000)^Math.floor(Math.random()*0xffffffff))>>>0)}
  function updateBuildHud(){var m=R.deriveModifiers(state.ownedUpgrades),levels=state.branchLevels;document.getElementById('run-code').textContent='RUN '+runCode(state.seed);document.getElementById('build-strip').textContent='PACK '+levels.pack+' · POP '+levels.pop+' · PANIC '+levels.panic;var effects=[];if(levels.pack)effects.push('성장 ×'+m.holdGrowth+(levels.pack>1?' · 금 +'+m.goldValue:'')+(levels.pack>2?' · 시작 +'+m.starterLoad:''));if(levels.pop)effects.push('릴레이 +'+m.relayReach+(levels.pop>1?' · 잔해 '+m.rubbleBridge:'')+(levels.pop>2?' · 표적 고정':''));if(levels.panic)effects.push('HIT '+m.perfectMultiplier+'×'+(levels.panic>2?' · 과열 '+Math.round(m.overheatFloor*100)+'%':''));document.getElementById('build-effect').textContent=effects.join(' / ')||'기본 장약';}
  function initLot(){lot=R.generateLot(seed,state.lotIndex);consumed=destroyed=packed=new Set();aim={x:4,y:3};fx.hits=[];updateBuildHud();announce(lot.name+', '+lot.trait.name+', 목표 '+lot.quota+'칸, 폭탄 3개')}
  function begin(seedArg){seed=typeof seedArg==='number'?(seedArg>>>0):freshSeed();state=R.start(R.newRun(seed));fx=freshFx();pointerDown=spaceHolding=pendingRelease=false;title.hidden=true;resultPanel.hidden=true;pausePanel.hidden=true;draftPanel.hidden=true;topbar.hidden=false;topbar.inert=false;machineHud.hidden=false;canvas.tabIndex=0;initLot();canvas.focus();announce('철거 시작. 누르고 압축, 떼어서 폭발.')}
  function startHold(){if(state.phase!=='playing'||state.paused)return;state=R.beginHold(state);if(state.holding){pointerDown=true;collectedStep=0;tone(110,.05,'sawtooth',.12);announce('압축 시작, 현재 '+state.blast+'칸')}}
  function collectNext(){var candidates=lot.cells.filter(function(c){return !consumed.has(c.id)&&(c.type==='gold'||c.type==='scrap')}).sort(function(a,b){return (Math.abs(a.x-aim.x)+Math.abs(a.y-aim.y))-(Math.abs(b.x-aim.x)+Math.abs(b.y-aim.y))});if(!candidates.length)return;var c=candidates[0],out=R.collectBlast(state,c.type);if(!out.change)return;state=out.state;consumed.add(c.id);fx.collect={text:out.change.before+' → '+out.change.after+' (+'+out.change.add+')',until:fx.clock+650};tone(c.type==='gold'?620:240,.08,'square',.06);announce((c.type==='gold'?'금빛 통':'고철')+' 수집: '+fx.collect.text)}
  function release(){pointerDown=false;if(!state.holding)return;if(state.paused){pendingRelease=true;return}pendingRelease=false;state=R.prepareRelease(state);if(state.phase==='exploding')explode()}
  function explode(){var p=state.preparedBlast,mods=R.deriveModifiers(state.ownedUpgrades),origin=R.targetOrigin(lot,aim,p.value,Array.from(consumed),mods);aim=origin;var prop=R.propagate(lot,origin,p.value,Array.from(consumed),mods),valid=prop.hitIds;fx.phaseMs=0;fx.tallyMs=0;fx.collect=null;fx.hits=valid.map(function(id,i){return{id:id,at:i*(reduced?18:28),done:false}});fx.shake=reduced?0:(state.branchLevels.pack===3||state.branchLevels.pop===3||state.branchLevels.panic===3?18:11);fx.stamp='WHAM! · '+(p.timing==='perfect'?'HIT! ×'+p.multiplier+' · ':'')+(p.timing==='overheat'?'과열 = '+Math.round(p.multiplier*100)+'% · ':'')+p.value+'칸';fx.stampUntil=state.ownedUpgrades.length===3?1350:1050;boom(p.timing);announce('이번 폭발 준비 '+p.value+'칸, 연쇄 폭발 시작')}
  function finishExplosion(){if(state.phase!=='exploding')return;var count=fx.hits.filter(function(h){return h.done}).length;state=R.applyExplosion(state,count);fx.tallyMs=0;announce('정산: '+state.preparedBlast.value+'칸 그대로 적용, '+count+'칸 철거')}
  function renderTree(){var html='';['pack','pop','panic'].forEach(function(branch){html+='<div class="tree-branch"><b>'+branch.toUpperCase()+'</b>';for(var tier=1;tier<=3;tier++){var u=R.UPGRADES[branch+'-'+tier],cls=state.ownedUpgrades.indexOf(u.id)>=0?'owned':state.offered.indexOf(u.id)>=0?'next':'';html+='<span class="'+cls+'">T'+tier+' '+u.name+'</span>'}html+='</div>'});document.getElementById('strategy-tree').innerHTML=html}
  function showDraft(){draftPanel.hidden=false;topbar.hidden=true;topbar.inert=true;canvas.tabIndex=-1;document.getElementById('draft-lot').textContent='LOT '+(state.lotIndex+1)+' CLEAR · 다음 LOT '+(state.lotIndex+2);var buttons=Array.from(document.querySelectorAll('#draft-options button'));buttons.forEach(function(button,i){var u=R.UPGRADES[state.offered[i]];button.dataset.upgrade=u.id;button.innerHTML='<b>'+u.branch.toUpperCase()+' · T'+u.tier+'</b><strong>'+u.ko+' / '+u.name+'</strong><small>'+u.effect+' : '+u.before+' → '+u.after+'</small>'});renderTree();buttons[0].focus();announce('업그레이드 선택. PACK, POP, PANIC 다음 단계 세 가지.')}
  function chooseUpgrade(id){var before=state;state=R.chooseUpgrade(state,id);if(state===before)return false;draftPanel.hidden=true;topbar.hidden=false;topbar.inert=false;canvas.tabIndex=0;initLot();canvas.focus();announce(R.UPGRADES[id].ko+' 장착. 다음 철거장.');return true}
  function finishTally(){if(state.phase!=='tally')return;var oldLot=state.lotIndex;state=R.finishTally(state);if(state.phase==='playing'){if(state.lotIndex!==oldLot)initLot();announce('남은 폭탄 '+state.charges+'개')}else if(state.phase==='draft')showDraft();else if(state.phase==='result')showResult()}
  function showResult(){var prepared=state.preparedBlast.value,actual=state.lastResult.destroyed;resultPanel.hidden=false;canvas.tabIndex=-1;document.getElementById('result-title').textContent=state.won?'완전 철거!':'철거 실패!';document.getElementById('result-copy').textContent=state.won?'네 구역이 먼지가 되었습니다. PERFECT DEMOLITION.':'목표를 못 채웠어요. 더 크게 꽉 눌러보세요.';document.getElementById('result-kicker').textContent=state.won?'현장 완료 · ALL CLEAR':'폭약 소진 · OUT OF CHARGES';document.getElementById('result-blast').textContent='이번 폭발 / THIS BLAST prepared '+prepared+'칸 → 실제 파괴 '+actual+'칸';document.getElementById('result-total').textContent='RUN TOTAL '+state.runDestroyed+' / '+state.runQuota+'칸 · '+runCode(state.seed);document.getElementById('replay').focus();announce(document.getElementById('result-title').textContent+', '+document.getElementById('result-blast').textContent)}
  function togglePause(owner){if(state.phase==='title'||state.phase==='result'||state.phase==='draft')return;state=R.setPaused(state,!state.paused,owner||'user');pausePanel.hidden=!state.paused;document.getElementById('pause').setAttribute('aria-pressed',String(state.paused));if(state.paused){document.getElementById('resume').focus();announce('일시정지')}else{canvas.focus();announce('계속하기');if(pendingRelease&&state.holding)release()}}
  function audioCtx(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
  function tone(freq,dur,type,vol,delay){if(muted)return;var a=audioCtx(),o=a.createOscillator(),g=a.createGain(),t=a.currentTime+(delay||0);o.type=type||'square';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.55),t+dur);g.gain.setValueAtTime(vol||.1,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(a.destination);o.start(t);o.stop(t+dur)}
  function boom(kind){tone(kind==='perfect'?95:75,.55,'sawtooth',.24);tone(48,.8,'square',.18,.04);tone(360,.12,'triangle',.08,.02)}
  function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
  function text(txt,x,y,size,color,align){ctx.font=size+'px Impact, Arial Black';ctx.textAlign=align||'left';ctx.fillStyle=color||'#26231f';ctx.fillText(txt,x,y)}
  function firstCharge(){return state.lotIndex===0&&state.charges===3&&state.destroyed===0&&!state.preparedBlast}
  function pill(txt,x,y,w){ctx.fillStyle='#fff5dc';rounded(x-w/2,y-20,w,32,5);ctx.fill();ctx.strokeStyle='#26231f';ctx.lineWidth=3;ctx.stroke();text(txt,x,y+3,15,'#26231f','center')}
  function tutorial(ox,oy,cw,ch,portraitMode){if(!firstCharge())return;var scrap=lot.cells.find(function(c){return c.type==='scrap'}),gold=lot.cells.find(function(c){return c.type==='gold'}),relay=lot.cells.find(function(c){return c.type==='relay'});function tag(c,label,dy,w){if(!c)return;var anchor=ox+c.x*cw+cw/2,x=R.clamp(anchor,w/2+10,LOGICAL_W-w/2-10),y=oy+c.y*ch+ch/2;ctx.strokeStyle='#26231f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(anchor,y);ctx.lineTo(x,y+dy);ctx.stroke();pill(label,x,y+dy+(dy<0?-5:18),w)}tag(scrap,'잔해 +1',portraitMode?-48:-42,82);tag(gold,'황금 드럼 +5칸',portraitMode?55:48,128);tag(relay,'릴레이 R = 연쇄 연결',portraitMode?-55:-48,155);pill('누르고 모으기 → 떼면 한 번에 폭발',portraitMode?270:480,portraitMode?862:530,portraitMode?390:410)}
  function background(){ctx.fillStyle='#f5e6c8';ctx.fillRect(0,0,960,540);ctx.strokeStyle='rgba(70,50,35,.08)';ctx.lineWidth=1;for(var y=0;y<540;y+=18){ctx.beginPath();ctx.moveTo(0,y+rnd(y)*3);ctx.lineTo(960,y);ctx.stroke()}ctx.fillStyle='#d7b77c';ctx.beginPath();ctx.moveTo(0,390);ctx.lineTo(140,300);ctx.lineTo(215,380);ctx.lineTo(350,270);ctx.lineTo(465,390);ctx.lineTo(625,285);ctx.lineTo(750,380);ctx.lineTo(870,250);ctx.lineTo(960,320);ctx.lineTo(960,540);ctx.lineTo(0,540);ctx.fill();ctx.strokeStyle='#26231f';ctx.lineWidth=5;ctx.stroke();for(var i=0;i<8;i++){ctx.fillStyle=i%2?'#26231f':'#f2b824';ctx.fillRect(i*150-30,420,90,120)}}
  function hud(){ctx.fillStyle='#26231f';ctx.fillRect(0,0,960,82);ctx.fillStyle='#f2b824';ctx.fillRect(0,76,960,6);text(lot.name+' / '+lot.en,22,25,18,'#fff5dc');text('목표 '+state.destroyed+' / '+state.quota+'칸',22,55,23,'#f2b824');pill(lot.trait.name+' / '+lot.trait.en,165,105,285);var n=state.holding?state.blast:(state.preparedBlast?state.preparedBlast.value:0);text('이번 폭발',480,25,18,'#fff5dc','center');text('THIS BLAST  '+n+'칸',480,64,38,'#f2b824','center');text('LOT '+(state.lotIndex+1)+'/4 · 폭탄 '+('● '.repeat(state.charges)),810,48,21,'#fff5dc','center')}
  function drawLot(now){var ox=188,oy=155,cw=66,ch=50,gold=R.deriveModifiers(state.ownedUpgrades).goldValue;lot.cells.forEach(function(c){if(destroyed.has(c.id)||packed.has(c.id))return;var x=ox+c.x*cw,y=oy+c.y*ch,j=(c.jitter%5)-2;ctx.save();ctx.translate(x+cw/2,y+ch/2);ctx.rotate(j*.012);ctx.translate(-cw/2,-ch/2);ctx.lineWidth=3;ctx.strokeStyle='#26231f';if(c.type==='gold'){ctx.fillStyle='#f2b824';rounded(13,5,40,43,8);ctx.fill();ctx.stroke();text('+'+gold,33,33,20,'#26231f','center')}else if(c.type==='relay'){ctx.fillStyle='#d94224';rounded(12,8,42,38,5);ctx.fill();ctx.stroke();text('R',33,36,25,'#fff5dc','center')}else if(c.type==='wall'){ctx.fillStyle='#7c7468';ctx.fillRect(5,6,56,40);ctx.strokeRect(5,6,56,40);ctx.beginPath();ctx.moveTo(5,6);ctx.lineTo(61,46);ctx.stroke()}else{ctx.fillStyle=(c.id%3===0)?'#8b9b91':'#b66f42';ctx.beginPath();ctx.moveTo(7,39);ctx.lineTo(12,10);ctx.lineTo(54,5);ctx.lineTo(61,37);ctx.lineTo(42,46);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()});
    var bx=ox+aim.x*cw+cw/2,by=oy+aim.y*ch+ch/2;ctx.fillStyle='#26231f';ctx.beginPath();ctx.arc(bx,by,24+(state.holding?Math.sin(now/90)*3:0),0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff5dc';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#d94224';ctx.beginPath();ctx.moveTo(bx+14,by-18);ctx.quadraticCurveTo(bx+23,by-39,bx+35,by-29);ctx.stroke();pill('폭탄 / BOMB',bx,by+67,112);tutorial(ox,oy,cw,ch,false)}
  function meter(){if(!state.holding)return;var m=R.deriveModifiers(state.ownedUpgrades),x=180,y=475,w=600,h=28,p=state.holdMs/3600,t=R.timingFor(state.holdMs,m),preview=t==='perfect'?state.blast*m.perfectMultiplier:t==='overheat'?Math.floor(state.blast*m.overheatFloor):state.blast;ctx.fillStyle='#fff5dc';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#26231f';ctx.lineWidth=4;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#f2b824';ctx.fillRect(x+2,y+2,(w-4)*p,h-4);ctx.fillStyle='rgba(217,66,36,.35)';ctx.fillRect(x+w*(m.perfectStart/3600),y,w*((m.perfectEnd-m.perfectStart)/3600),h);ctx.strokeStyle='#d94224';ctx.strokeRect(x+w*(m.perfectStart/3600),y,w*((m.perfectEnd-m.perfectStart)/3600),h);text('HIT! ×'+m.perfectMultiplier,x+w*((m.perfectStart+m.perfectEnd)/2/3600),y-8,18,'#d94224','center');text('과열 = '+Math.round(m.overheatFloor*100)+'%',x+w,y-8,17,'#26231f','right');text('누르는 중: '+state.blast+'칸 → 떼면 '+preview+'칸',480,455,26,'#26231f','center')}
  function portraitScene(now){ctx.fillStyle='#f5e6c8';ctx.fillRect(0,0,540,960);ctx.strokeStyle='rgba(70,50,35,.09)';for(var py=0;py<960;py+=24){ctx.beginPath();ctx.moveTo(0,py);ctx.lineTo(540,py);ctx.stroke()}ctx.fillStyle='#26231f';ctx.fillRect(0,0,540,194);ctx.fillStyle='#f2b824';ctx.fillRect(0,187,540,7);if(!lot)return;text(lot.name+' · LOT '+(state.lotIndex+1)+'/4',18,30,19,'#fff5dc');text('목표 '+state.destroyed+' / '+state.quota+'칸',18,61,25,'#f2b824');text(lot.trait.name+' / '+lot.trait.en,18,91,15,'#fff5dc');text('폭탄 '+('● '.repeat(state.charges)),18,119,17,'#fff5dc');var n=state.holding?state.blast:(state.preparedBlast?state.preparedBlast.value:0);text('이번 폭발 / THIS BLAST',270,145,19,'#fff5dc','center');text(n+'칸',270,184,42,'#f2b824','center');var ox=27,oy=238,cw=54,ch=76;lot.cells.forEach(function(c){if(destroyed.has(c.id)||packed.has(c.id))return;var x=ox+c.x*cw,y=oy+c.y*ch;ctx.save();ctx.translate(x+25,y+29);ctx.rotate(((c.jitter%5)-2)*.015);ctx.translate(-25,-29);ctx.strokeStyle='#26231f';ctx.lineWidth=3;ctx.fillStyle=c.type==='gold'?'#f2b824':c.type==='relay'?'#d94224':c.type==='wall'?'#817b70':(c.id%3?'#b66f42':'#8b9b91');rounded(3,3,48,58,6);ctx.fill();ctx.stroke();if(c.type==='gold')text('+'+R.deriveModifiers(state.ownedUpgrades).goldValue,27,40,18,'#26231f','center');if(c.type==='relay')text('R',27,42,24,'#fff5dc','center');if(c.type==='wall'){ctx.beginPath();ctx.moveTo(5,5);ctx.lineTo(49,59);ctx.stroke()}ctx.restore()});var bx=ox+aim.x*cw+27,by=oy+aim.y*ch+31;ctx.fillStyle='#26231f';ctx.beginPath();ctx.arc(bx,by,25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff5dc';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='#d94224';ctx.beginPath();ctx.moveTo(bx+14,by-18);ctx.quadraticCurveTo(bx+24,by-39,bx+36,by-28);ctx.stroke();pill('폭탄 / BOMB',R.clamp(bx,56,LOGICAL_W-56),by+65,112);tutorial(ox,oy,cw,ch,true);if(state.holding){var m=R.deriveModifiers(state.ownedUpgrades),mx=42,my=905,mw=456,p=state.holdMs/3600;ctx.fillStyle='#fff5dc';ctx.fillRect(mx,my,mw,28);ctx.strokeStyle='#26231f';ctx.strokeRect(mx,my,mw,28);ctx.fillStyle='#f2b824';ctx.fillRect(mx+2,my+2,(mw-4)*p,24);ctx.fillStyle='rgba(217,66,36,.45)';ctx.fillRect(mx+mw*m.perfectStart/3600,my,mw*(m.perfectEnd-m.perfectStart)/3600,28);text('HIT! ×'+m.perfectMultiplier,mx+mw*(m.perfectStart+m.perfectEnd)/7200,my-8,17,'#d94224','center');text('과열 = '+Math.round(m.overheatFloor*100)+'%',mx+mw,my-8,16,'#26231f','right')}if(fx.collect&&now<fx.collect.until)pill(fx.collect.text,270,218,250);drawExplosionFx(now,true)}
  function blastStar(x,y,r1,r2,points){ctx.beginPath();for(var i=0;i<points*2;i++){var a=-Math.PI/2+i*Math.PI/points,r=i%2?r2:r1;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r)}ctx.closePath()}
  function drawExplosionFx(now,isPortrait){var age=fx.phaseMs;if(state.phase!=='exploding'&&state.phase!=='tally')return;var ox=isPortrait?27:188,oy=isPortrait?238:155,cw=isPortrait?54:66,ch=isPortrait?76:50,centerX=ox+aim.x*cw+cw/2,centerY=oy+aim.y*ch+ch/2,t3=state.ownedUpgrades.length===3?1.18:1,scale=(isPortrait?.82:1)*t3;fx.hits.forEach(function(h){if(age<h.at||age-h.at>=430)return;var c=lot.cells[h.id],x=ox+c.x*cw+cw/2,y=oy+c.y*ch+ch/2,t=(age-h.at)/430;ctx.strokeStyle='rgba(255,245,220,'+(1-t)+')';ctx.lineWidth=14*(1-t)+3;blastStar(x,y,(24+t*50)*scale,(13+t*30)*scale,9);ctx.stroke()});if(age>=0&&age<820){var pulse=reduced?1:1+Math.sin(age/45)*.06,fade=Math.max(0,1-age/900);ctx.save();ctx.globalAlpha=fade;ctx.fillStyle='#d94224';blastStar(centerX,centerY,155*scale*pulse,105*scale*pulse,14);ctx.fill();ctx.fillStyle='#f2b824';blastStar(centerX,centerY,120*scale,82*scale,12);ctx.fill();ctx.fillStyle='#fff5dc';ctx.beginPath();ctx.arc(centerX,centerY,72*scale,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#26231f';ctx.lineWidth=7;for(var j=0;j<18;j++){var a=j*Math.PI*2/18,inner=170*scale,outer=(210+(j%3)*18)*scale;ctx.beginPath();ctx.moveTo(centerX+Math.cos(a)*inner,centerY+Math.sin(a)*inner);ctx.lineTo(centerX+Math.cos(a)*outer,centerY+Math.sin(a)*outer);ctx.stroke()}ctx.restore()}fx.particles.forEach(function(p){ctx.fillStyle=p.color;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.life*.18);ctx.fillRect(-6,-3,16,8);ctx.restore()});var chain=fx.hits.filter(function(h){return h.done}).length;if(state.phase==='exploding'){pill('CHAIN '+chain+' / '+fx.hits.length,isPortrait?270:480,isPortrait?220:130,isPortrait?210:240);if(age<fx.stampUntil)pill(fx.stamp,isPortrait?410:820,isPortrait?214:125,isPortrait?220:230)}}
  function drawFx(now){drawExplosionFx(now,false);if(fx.collect&&now<fx.collect.until)pill(fx.collect.text,480,128,270)}
  function render(now){ctx.save();var shakeKey=fx.clock,sx=fx.shake>0?(rnd(shakeKey)-.5)*fx.shake:0,sy=fx.shake>0?(rnd(shakeKey+2)-.5)*fx.shake:0;if(!reduced)ctx.translate(sx,sy);if(portrait){portraitScene(now)}else{background();if(lot){hud();drawLot(now);meter();drawFx(now)}}ctx.restore();requestAnimationFrame(render)}
  function advanceSimulation(dt){var frames=dt/16.667;fx.clock+=dt;fx.shake*=Math.pow(.91,frames);if(state.holding){state=R.advanceHold(state,dt);var step=Math.floor(state.holdMs/600);while(collectedStep<step){collectedStep++;collectNext()}if(state.holdMs>=3600)release()}if(state.phase==='exploding'){fx.phaseMs+=dt;fx.hits.forEach(function(h,i){if(h.done||fx.phaseMs<h.at)return;h.done=true;consumed.add(h.id);var c=lot.cells[h.id],ox=portrait?27:188,oy=portrait?238:155,cw=portrait?54:66,ch=portrait?76:50,x=ox+c.x*cw+cw/2,y=oy+c.y*ch+ch/2;for(var k=0;k<(reduced?4:14);k++)fx.particles.push({x:x,y:y,vx:(rnd(h.id*31+k)-.5)*11,vy:-rnd(h.id*71+k)*9-2,life:46,color:k%4===0?'#fff5dc':k%2?'#d94224':'#f2b824'});tone(90+i%4*35,.09,'square',.035)});if((!fx.hits.length&&fx.phaseMs>=300)||(fx.hits.length&&fx.hits.every(function(h){return h.done})&&fx.phaseMs>fx.hits[fx.hits.length-1].at+480))finishExplosion()}else if(state.phase==='tally'){fx.tallyMs+=dt;if(fx.tallyMs>=650)finishTally()}var frames=dt/16.667;fx.particles.forEach(function(p){p.x+=p.vx*frames;p.y+=p.vy*frames;p.vy+=.38*frames;p.life-=frames});fx.particles=fx.particles.filter(function(p){return p.life>0})}
  function tick(now){var dt=Math.min(50,now-last);last=now;if(!state.paused&&state.phase!=='draft'&&state.phase!=='title'&&state.phase!=='result')advanceSimulation(dt);requestAnimationFrame(tick)}
  function setAimFromEvent(e){if(!lot)return;var r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*LOGICAL_W,y=(e.clientY-r.top)/r.height*LOGICAL_H;aim.x=R.clamp(Math.floor((x-(portrait?27:188))/(portrait?54:66)),0,8);aim.y=R.clamp(Math.floor((y-(portrait?238:155))/(portrait?76:50)),0,5)}
  canvas.addEventListener('pointerdown',function(e){e.preventDefault();setAimFromEvent(e);canvas.setPointerCapture(e.pointerId);startHold()});canvas.addEventListener('pointermove',function(e){if(!pointerDown)setAimFromEvent(e)});canvas.addEventListener('pointerup',function(e){e.preventDefault();release()});canvas.addEventListener('pointercancel',release);
  function interactiveTarget(target){return target&&target.closest&&target.closest('button,input,select,textarea,a[href],[role="button"]')}
  addEventListener('keydown',function(e){if(state.phase==='draft'&&e.key==='Tab'){var buttons=Array.from(document.querySelectorAll('#draft-options button')),i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();return}if(e.code==='Space'&&!e.repeat&&!interactiveTarget(e.target)&&state.phase==='playing'){e.preventDefault();spaceHolding=true;startHold()}if((e.code==='Escape'||e.code==='KeyP')&&state.phase!=='draft'){e.preventDefault();togglePause('user')}});addEventListener('keyup',function(e){if(e.code==='Space'&&spaceHolding){e.preventDefault();spaceHolding=false;release()}});
  document.getElementById('start').onclick=function(){begin()};document.getElementById('replay').onclick=function(){begin()};document.querySelectorAll('#draft-options button').forEach(function(button){button.onclick=function(){chooseUpgrade(this.dataset.upgrade)}});document.getElementById('pause').onclick=function(){togglePause('user')};document.getElementById('resume').onclick=function(){togglePause(state.pauseOwner)};document.getElementById('mute').onclick=function(){muted=!muted;this.setAttribute('aria-pressed',String(muted));this.setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');announce(muted?'소리 꺼짐':'소리 켜짐')};
  document.addEventListener('visibilitychange',function(){if(document.hidden&&!state.paused&&!['title','result','draft'].includes(state.phase)){state=R.setPaused(state,true,'visibility');pausePanel.hidden=false;document.getElementById('pause').setAttribute('aria-pressed','true')}else if(!document.hidden&&state.paused&&state.pauseOwner==='visibility'){announce('화면 복귀. 계속하기 버튼을 누르세요.')}});
  function geometry(){var ox=portrait?27:188,oy=portrait?238:155,cw=portrait?54:66,ch=portrait?76:50,bx=ox+aim.x*cw+cw/2,by=oy+aim.y*ch+ch/2,labelX=portrait?R.clamp(bx,56,LOGICAL_W-56):bx;return{viewport:{x:0,y:0,w:LOGICAL_W,h:LOGICAL_H},hud:{x:0,y:0,w:LOGICAL_W,h:portrait?194:82},grid:{x:ox,y:oy,w:cw*9,h:ch*6},bomb:{x:bx-27,y:by-27,w:54,h:54},bombLabel:{x:labelX-56,y:by+45,w:112,h:32},instruction:{x:portrait?75:275,y:portrait?842:510,w:portrait?390:410,h:32}}}
  window.__PACK_POP_DEBUG__=Object.freeze({snapshot:function(){var snap={seed:state.seed,lotIndex:state.lotIndex,trait:lot?lot.trait:null,phase:state.phase,offered:state.offered.slice(),ownedUpgradeIds:state.ownedUpgrades.slice(),branchLevels:state.branchLevels,derivedModifiers:R.deriveModifiers(state.ownedUpgrades),preparedValue:state.holding?state.blast:0,frozenValue:state.preparedBlast?state.preparedBlast.value:null,quotas:{lot:state.quota,run:state.runQuota,destroyed:state.destroyed,runDestroyed:state.runDestroyed},state:state,aim:aim,consumed:Array.from(consumed),destroyed:Array.from(consumed),effects:{clock:fx.clock,phaseMs:fx.phaseMs,tallyMs:fx.tallyMs,shake:fx.shake,hitDone:fx.hits.map(function(h){return h.done}),particles:fx.particles.map(function(p){return{x:p.x,y:p.y,vx:p.vx,vy:p.vy,life:p.life}})},backing:{width:canvas.width,height:canvas.height},css:{width:canvas.clientWidth,height:canvas.clientHeight},geometry:geometry()};return Object.freeze(JSON.parse(JSON.stringify(snap)))},start:function(debugSeed){if(debugSeed===undefined)return false;begin(Number(debugSeed)>>>0);return this.snapshot()},hold:startHold,release:release,advance:function(ms){if(state.paused||['draft','title','result'].includes(state.phase))return this.snapshot();var remaining=Math.max(0,Math.min(ms,4000));while(remaining>0){var step=Math.min(16.667,remaining);advanceSimulation(step);remaining-=step}return this.snapshot()},setAim:function(x,y){aim={x:R.clamp(x|0,0,8),y:R.clamp(y|0,0,5)};return this.snapshot()},choose:function(id){chooseUpgrade(id);return this.snapshot()}});
  requestAnimationFrame(render);requestAnimationFrame(tick);
})();
